# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-25 10:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('comment', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('breed', models.CharField(max_length=250)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('color', models.CharField(max_length=250)),
                ('dob', models.DateField()),
                ('location', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold Out')], default=('Available', 'Available'), max_length=150)),
                ('sold_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('views', models.BigIntegerField(default=0)),
                ('upvotes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductWanted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('breed', models.CharField(max_length=250)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('No Preference', 'No preference')], max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('color', models.CharField(max_length=250)),
                ('dob', models.DateField()),
                ('location', models.CharField(max_length=250)),
                ('status', models.CharField(blank=True, choices=[('Looking', 'Looking'), ('Found', 'Found!')], default=('Looking', 'Looking'), max_length=150)),
                ('sold_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('views', models.BigIntegerField(default=0)),
                ('upvotes', models.IntegerField(default=0)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.ProductWanted'),
        ),
    ]
