# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-02 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productselling',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
