# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-02 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191002_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productselling',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('No preference', 'No preference')], max_length=150),
        ),
        migrations.AlterField(
            model_name='productwanted',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
